### ISSUE TITLE
'data_dir' in training_args.bin

### ISSUE THREAD

**Issue by mrzhang11** [martiansideofthemoon/style-transfer-paraphrase#1]
Dear authors,

thanks for your contributions and the work is really interesting. When I checked the training_args.bin, there exists several arguments that are personal directories such as data_dir, output_dir,roberta_pretrained...
<img width="753" alt="Snipaste_2020-11-02_11-49-24" src="https://user-images.githubusercontent.com/14029774/97859912-8e081800-1d01-11eb-94f3-3e83d71b8ab9.png">

It will introduce some exceptions when running demo_paraphrase.py:
![image](https://user-images.githubusercontent.com/14029774/97860018-b8f26c00-1d01-11eb-89af-a28319671e54.png)

What's more, there should be some files under the data_dir but they were not uploaded. Could you solve this issue later?

Thanks!

**Comment by martiansideofthemoon** [comment]
Thanks for reaching out! This is a bug introduced in my recent commits, I'm pushing a fix soon.

**Comment by martiansideofthemoon** [comment]
Fixed in 64fbf5d54f59013a7cf5413e5dd679ead0875922.
