### ISSUE TITLE
the vocab file

### ISSUE THREAD

**Issue by mrzhang11** [martiansideofthemoon/style-transfer-paraphrase#3]
Hey,

For the datasets of Corpus of Diverse Styles, since only bpe and label files are uploaded, I was wondering that if u could also upload the bpe vocab file as well? Or are there any rules or restrictions?

**Comment by mrzhang11** [comment]
Just ignore my stupid question. I found the files under the models directory...

**Comment by martiansideofthemoon** [comment]
Thanks for mentioning this! yes a bit more work is needed on the repository (especially related to CDS, the BPE processing instructions and custom data preprocessing), I hope to get to it next week.
