### ISSUE TITLE
Model and checkpoints - correct names based on each training corpus

### ISSUE THREAD

**Issue by GenTxt** [martiansideofthemoon/style-transfer-paraphrase#4]
Thanks for the great repo and models.

I've downloaded all models and scripts from the google drive link and I'm trying to organize the 16 large models and 4 checkpoints. I would like to know which models/checkpoints correspond to the correct corpus used in training. 

For example, Shakespeare, James Joyce, Romantic Poetry, 1890-1910 historical English, 1990-2010 historical English.
Is it possible to match the list below to the correct corpus used?

pytorch_model-002.bin	
pytorch_model-003.bin	
pytorch_model-004.bin	
pytorch_model-006.bin
pytorch_model-007.bin  
pytorch_model-008.bin  	
pytorch_model-009.bin  
pytorch_model-010.bin  
pytorch_model-012.bin  
pytorch_model-014.bin 
pytorch_model-015.bin 
pytorch_model-016.bin
pytorch_model-017.bin
pytorch_model-018.bin
pytorch_model-019.bin
pytorch_model-021.bin

checkpoint_best-005.pt	
checkpoint_best-011.pt
checkpoint_best-013.pt
checkpoint_best-020.pt

Also, there are 4 model folder options:

models/

cds_models
formality_models		
paraphraser_gpt2_large
shakespeare_models

Are all of the above models/checkpoints placed in 'paraphraser_gpt2_large' to run:

python demo_paraphraser.py --model_dir paraphraser_gpt2_large --top_p_value 0.6

Cheers

**Comment by mrzhang11** [comment]
Hey, did u create the suffix numbers by yourself? Because the models are given under the corresponding directories in the provided link.

**Comment by GenTxt** [comment]
Strange. That's the way they were auto-renamed when I downloaded everything from 'style_transfer_paraphrase' at the top level using the link. The corresponding directories included config files etc. but not the matching model. Could you post the list so I can place the correct models in the matching folders ?  Cheers.

**Comment by GenTxt** [comment]
The problem appears to be the google drive 2+ gig limit for each file. Requesting almost 75 gigs in a single zip causes google drive to break out these files from the zip. Using ubuntu 18.04. Tried again downloading 'models' folder only and same result. Each model/checkpoint was auto-renamed sequentially  (in the order it appears in the zip archive?) Will have to search for solution. Maybe the renaming order is a clue to the correct folder? Would also suggest 1 archive per folder. Easier to download and match model if needed.

**Comment by mrzhang11** [comment]
Hi, I am not sure if this will solve your confusion, but for example, here is the link to the AAE pre-trained model: https://drive.google.com/drive/folders/1pADytwngC9AZcsYoMk0V-uVMiE0jEz4F, and u can see the pytorch_model.bin (I didn't run it yet)

And u can download all of them from the link mentioned in README.

**Comment by GenTxt** [comment]
Thanks. Downloading each from correct folder on google drive.  Closing issue.

Cheers
