### ISSUE TITLE
Unable to run custom datasets

### ISSUE THREAD

**Issue by aflah02** [martiansideofthemoon/style-transfer-paraphrase#40]
After running all the steps listed to run the code for a custom dataset when I finally ran `python style_paraphrase/schedule.py` I got the following error - 
`subprocess.CalledProcessError: Command 'sbatch style_paraphrase/slurm-schedulers/schedule_0.sh' returned non-zero exit status 127.` 
For the last step I had added `"datasets/new_dataset": BASE_CONFIG` into `DATASET_CONFIG` and changed `[('dataset',), ["datasets/formality"]]` to `[('dataset',), ["datasets/new_dataset"]]`, inside `hyperparameters_config.py`

I'm not quite sure what the error indicates and how Should I Proceed from here on

**Comment by martiansideofthemoon** [comment]
Hi @aflah02,
What happens when you run `sbatch style_paraphrase/slurm-schedulers/schedule_0.sh` on the terminal? Do you have SLURM on your machine?

**Comment by aflah02** [comment]
Oh yes it turns out the server does not have SLURM installed
I'll retry once it's installed 
Thanks for the quick reply

**Comment by HassanBinAli** [comment]
Can you kindly tell how to install SLURM? I am working on Colab.

**Comment by martiansideofthemoon** [comment]
Slurm is optional while using the bash scripts, just run script with bash if you don't have slurm. To install slurm follow https://slurm.schedmd.com/quickstart_admin.html
