### ISSUE TITLE
Style transfer on french text

### ISSUE THREAD

**Issue by zaouch** [martiansideofthemoon/style-transfer-paraphrase#41]
Hi,

Would the pytorch model file located in the multilingual folder work for applying the algorithm on french ?

Thank you.

**Comment by martiansideofthemoon** [comment]
Hi, do you mean for style classification? We have tested style classification on French here - https://github.com/martiansideofthemoon/style-transfer-paraphrase/blob/master/README-multilingual.md

**Comment by zaouch** [comment]
Thanks,I am interested in style paraphrasing on french. Is your program still applicable to this task ?

**Comment by martiansideofthemoon** [comment]
You will need to re-train the models on French data, and/or use a multilingual initialization like mT5 (https://huggingface.co/docs/transformers/model_doc/mt5).
