### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'paraphraser_gpt2_large/training_args.bin'

### ISSUE THREAD

**Issue by OliveS9** [martiansideofthemoon/style-transfer-paraphrase#42]
Could you please help with fixing the following error when trying to run "demo_paraphraser.py"?

     FileNotFoundError: [Errno 2] No such file or directory: 'paraphraser_gpt2_large/training_args.bin'

Thanks a lot!

**Comment by martiansideofthemoon** [comment]
Hi @OliveS9, you would need to download the model / args file from the Drive folder link in README (https://drive.google.com/drive/folders/1RmiXX8u1ojj4jorj_QgxOWWkryDIdie-?usp=sharing). Let me know if you have any further questions.
