### ISSUE TITLE
Can't find my fine tuned pytorch model

### ISSUE THREAD

**Issue by HassanBinAli** [martiansideofthemoon/style-transfer-paraphrase#49]
I have fine tuned the model on custom dataset using GPT2-medium. But when I run `!python demo_paraphraser.py --model_dir style_paraphrase/saved_models/test_paraphrase/checkpoint-10000`, it gives
![image](https://user-images.githubusercontent.com/87352841/217451593-11d00e63-84be-4b3b-a4b1-e27cf77a3d88.png)

**Comment by martiansideofthemoon** [comment]
could you `ls` that checkpoint directory and share output? All files should be [in this link](https://drive.google.com/drive/folders/1RmiXX8u1ojj4jorj_QgxOWWkryDIdie-?usp=share_link).

**Comment by HassanBinAli** [comment]
Hey! So I deleted everything (every folder every file) and did all from scratch again. This solved the issue. Every necessary file is there in right folder and the fine tuned model is making predictions. Thank you for you work and help.

**Comment by martiansideofthemoon** [comment]
great! good luck with your experiments
